name: anubis
version: git
summary: Anubis
description: |
  Subdomain enumeration and information gathering tool

confinement: strict
grade: stable

apps:
  anubis:
    command: anubis

parts:
  anubis:
    plugin: python
    python-version: python3
    build-packages:
    - python3-pip
    - python-dev
    - libssl-dev
    - libffi-dev
    source: .